### PR TITLE
Add module storage

### LINKED ISSUE #23: As a user, I should be able to store information about modules
- For the developers this entails adding a Module model

### PR DESCRIPTION
**Pull request by yadunut**
WIP PR to add module storage. This works by
1. adding a new `JsonModuleMapStorage` which handles reading the JSON file from within the resources
    - The path is hardcoded and not parameterised as this file is not updatable. 
    - This returns a ModuleMap, a mapping of `ModuleCode` to `Module`. 
2. Separates the storage layer and the Model layer with `JsonAdaptedModule` and `Module` 

Closes #32 
Closes #23

### CODE REVIEW

**Comment by taufiq** [comment]
Holy cowabunga! This is a heavy PR 😮 Will get on it ASAP! 🤠

**Review by blaukc — APPROVED** [review]
LGTM! Thanks for fixing my code LOL. Maybe taufiq can look thru first as well then merge since its good to read thru before doing his part i feel.

**Comment by yadunut** [comment]
> Thanks for fixing my code LOL.

There isn't anything particularly wrong with the way you did, its how I would have done in almost any other project. In this project, they are very explicit with their separation between the Model and Storage, and thus, the code is extremely verbose as seen above. There are benefits to doing it like this, for example, when you'll be implementing the student <-> module integration. We can have completely different representations at the Model Layer as compared to the Storage Layer. Whereas if the JSON structures was embedded in the Model and Student, it would be very hard to separate the storage representation and the Model representation of our data.

**Review by taufiq — APPROVED** [review]
lgtm

**Pull request merged**
