### PR TITLE
docs: Remove traces of AB3 from README

### PR DESCRIPTION
**Pull request by taufiq**
This commit removes the traces of AB3 in README that was pointed out in the cs2103 tracker.

### CODE REVIEW

**Review by yadunut — APPROVED** [review]
LGTM!

**Comment by taufiq** [comment]
Sui

**Comment by AdityaB4** [comment]
We might need to remove the reference to AB3 in the acknowledgement as well, we can come back to this if the tracker does not update still.

**Comment by blaukc** [comment]
> We might need to remove the reference to AB3 in the acknowledgement as well, we can come back to this if the tracker does not update still.

The other groups did the same I think

**Pull request merged**
