### PR TITLE
Update docs to explain tags can not process white spaces

### LINKED ISSUE #82: [PE-D][Tester A] Tag is unable to accept string with space inside
When attempting to edit or add a student with a tag, it does not accept tags with spacing inbetween them.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: DominicFuMJ/ped#3

### PR DESCRIPTION
**Pull request by AdityaB4**
Fixes #82. @AY2324S2-CS2103T-W12-2/developers can someone help check whitespaces don't create unrecoverable states in the app.

### CODE REVIEW

**Comment by blaukc** [comment]
> Fixes #82. @AY2324S2-CS2103T-W12-2/developers can someone help check whitespaces don't create unrecoverable states in the app.

what does unrecoverable states mean & how are they created

**Comment by yadunut** [comment]
As of now, tag names only support alphanumeric characters, so underscore doesn't work

**Comment by AdityaB4** [comment]
> As of now, tag names only support alphanumeric characters, so underscore doesn't work

@yadunut would it be right to change this to just say whitespaces are not accepted then?

**Comment by yadunut** [comment]
I think if you change it to "You can use capitalization such as camelCasing" to distinguish different words in a tag and the **no whitespaces** part and then write a line in the glossary about camelCasing

**Review by blaukc — APPROVED** [review]

**Pull request merged**
